// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: client.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
insert into client (
    first_name,
    second_name,
    family_name,
    age,
    phone_number,
    profession_1,
    profession_2,
    company,
    university,
    password_hash
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
returning id, first_name, second_name, family_name, age, phone_number, profession_1, profession_2, company, future, university, description, password_hash
`

type CreateClientParams struct {
	FirstName    string  `json:"first_name"`
	SecondName   string  `json:"second_name"`
	FamilyName   string  `json:"family_name"`
	Age          int32   `json:"age"`
	PhoneNumber  string  `json:"phone_number"`
	Profession1  *string `json:"profession_1"`
	Profession2  *string `json:"profession_2"`
	Company      *string `json:"company"`
	University   *string `json:"university"`
	PasswordHash string  `json:"password_hash"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.FirstName,
		arg.SecondName,
		arg.FamilyName,
		arg.Age,
		arg.PhoneNumber,
		arg.Profession1,
		arg.Profession2,
		arg.Company,
		arg.University,
		arg.PasswordHash,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.SecondName,
		&i.FamilyName,
		&i.Age,
		&i.PhoneNumber,
		&i.Profession1,
		&i.Profession2,
		&i.Company,
		&i.Future,
		&i.University,
		&i.Description,
		&i.PasswordHash,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
delete from client
where id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClientByID = `-- name: GetClientByID :one
select id, first_name, second_name, family_name, age, phone_number, profession_1, profession_2, company, future, university, description, password_hash from client
where id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.SecondName,
		&i.FamilyName,
		&i.Age,
		&i.PhoneNumber,
		&i.Profession1,
		&i.Profession2,
		&i.Company,
		&i.Future,
		&i.University,
		&i.Description,
		&i.PasswordHash,
	)
	return i, err
}

const getClientByPhone = `-- name: GetClientByPhone :one
select id, first_name, second_name, family_name, age, phone_number, profession_1, profession_2, company, future, university, description, password_hash from client
where phone_number = $1
`

func (q *Queries) GetClientByPhone(ctx context.Context, phoneNumber string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByPhone, phoneNumber)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.SecondName,
		&i.FamilyName,
		&i.Age,
		&i.PhoneNumber,
		&i.Profession1,
		&i.Profession2,
		&i.Company,
		&i.Future,
		&i.University,
		&i.Description,
		&i.PasswordHash,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :one
update client
set
    first_name   = coalesce($2, first_name),
    second_name  = coalesce($3, second_name),
    family_name  = coalesce($4, family_name),
    age          = coalesce($5, age),
    phone_number = coalesce($6, phone_number),
    profession_1 = coalesce($7, profession_1),
    profession_2 = coalesce($8, profession_2),
    company      = coalesce($9, company),
    future      = coalesce($10, future),
    university   = coalesce($11, university),
    description  = coalesce($12, description)
where
    id = $1
returning id, first_name, second_name, family_name, age, phone_number, profession_1, profession_2, company, future, university, description, password_hash
`

type UpdateClientParams struct {
	ID          uuid.UUID `json:"id"`
	FirstName   *string   `json:"first_name"`
	SecondName  *string   `json:"second_name"`
	FamilyName  *string   `json:"family_name"`
	Age         *int32    `json:"age"`
	PhoneNumber *string   `json:"phone_number"`
	Profession1 *string   `json:"profession_1"`
	Profession2 *string   `json:"profession_2"`
	Company     *string   `json:"company"`
	Future      *string   `json:"future"`
	University  *string   `json:"university"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.FirstName,
		arg.SecondName,
		arg.FamilyName,
		arg.Age,
		arg.PhoneNumber,
		arg.Profession1,
		arg.Profession2,
		arg.Company,
		arg.Future,
		arg.University,
		arg.Description,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.SecondName,
		&i.FamilyName,
		&i.Age,
		&i.PhoneNumber,
		&i.Profession1,
		&i.Profession2,
		&i.Company,
		&i.Future,
		&i.University,
		&i.Description,
		&i.PasswordHash,
	)
	return i, err
}
