// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: club.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createClub = `-- name: CreateClub :one
insert into club (
    owner_id,
    name,
    specs,
    description,
    tg_url,
    logo_url,
    admin_contact,
    from_org
) values (
    $1, $2, $3, $4, $5, $6, $7, $8
)
returning id, owner_id, name, specs, description, tg_url, logo_url, admin_contact, from_org
`

type CreateClubParams struct {
	OwnerID      uuid.UUID `json:"owner_id"`
	Name         string    `json:"name"`
	Specs        string    `json:"specs"`
	Description  string    `json:"description"`
	TgUrl        string    `json:"tg_url"`
	LogoUrl      string    `json:"logo_url"`
	AdminContact string    `json:"admin_contact"`
	FromOrg      bool      `json:"from_org"`
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, createClub,
		arg.OwnerID,
		arg.Name,
		arg.Specs,
		arg.Description,
		arg.TgUrl,
		arg.LogoUrl,
		arg.AdminContact,
		arg.FromOrg,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Specs,
		&i.Description,
		&i.TgUrl,
		&i.LogoUrl,
		&i.AdminContact,
		&i.FromOrg,
	)
	return i, err
}

const deleteClub = `-- name: DeleteClub :exec
delete from club where id = $1
`

func (q *Queries) DeleteClub(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClub, id)
	return err
}

const getClubByID = `-- name: GetClubByID :one
select 
    c.id, c.owner_id, c.name, c.specs, c.description, c.tg_url, c.logo_url, c.admin_contact, c.from_org,
    o.name as org_name
from club c
left join org o on c.owner_id = o.user_id and c.from_org = true
where c.id = $1
`

type GetClubByIDRow struct {
	ID           uuid.UUID `json:"id"`
	OwnerID      uuid.UUID `json:"owner_id"`
	Name         string    `json:"name"`
	Specs        string    `json:"specs"`
	Description  string    `json:"description"`
	TgUrl        string    `json:"tg_url"`
	LogoUrl      string    `json:"logo_url"`
	AdminContact string    `json:"admin_contact"`
	FromOrg      bool      `json:"from_org"`
	OrgName      *string   `json:"org_name"`
}

func (q *Queries) GetClubByID(ctx context.Context, id uuid.UUID) (GetClubByIDRow, error) {
	row := q.db.QueryRow(ctx, getClubByID, id)
	var i GetClubByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Specs,
		&i.Description,
		&i.TgUrl,
		&i.LogoUrl,
		&i.AdminContact,
		&i.FromOrg,
		&i.OrgName,
	)
	return i, err
}

const getClubsByOwner = `-- name: GetClubsByOwner :many
select 
    c.id, c.owner_id, c.name, c.specs, c.description, c.tg_url, c.logo_url, c.admin_contact, c.from_org,
    o.name as org_name
from club c
left join org o on c.owner_id = o.user_id and c.from_org = true
where c.owner_id = $1
`

type GetClubsByOwnerRow struct {
	ID           uuid.UUID `json:"id"`
	OwnerID      uuid.UUID `json:"owner_id"`
	Name         string    `json:"name"`
	Specs        string    `json:"specs"`
	Description  string    `json:"description"`
	TgUrl        string    `json:"tg_url"`
	LogoUrl      string    `json:"logo_url"`
	AdminContact string    `json:"admin_contact"`
	FromOrg      bool      `json:"from_org"`
	OrgName      *string   `json:"org_name"`
}

func (q *Queries) GetClubsByOwner(ctx context.Context, ownerID uuid.UUID) ([]GetClubsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getClubsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClubsByOwnerRow
	for rows.Next() {
		var i GetClubsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Specs,
			&i.Description,
			&i.TgUrl,
			&i.LogoUrl,
			&i.AdminContact,
			&i.FromOrg,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClub = `-- name: UpdateClub :one
update club set
    name = coalesce($2, name),
    specs = coalesce($3, specs),
    description = coalesce($4, description),
    tg_url = coalesce($5, tg_url),
    logo_url = coalesce($6, logo_url),
    admin_contact = coalesce($7, admin_contact),
    from_org = coalesce($8, from_org)
where id = $1
returning id, owner_id, name, specs, description, tg_url, logo_url, admin_contact, from_org
`

type UpdateClubParams struct {
	ID           uuid.UUID `json:"id"`
	Name         *string   `json:"name"`
	Specs        *string   `json:"specs"`
	Description  *string   `json:"description"`
	TgUrl        *string   `json:"tg_url"`
	LogoUrl      *string   `json:"logo_url"`
	AdminContact *string   `json:"admin_contact"`
	FromOrg      *bool     `json:"from_org"`
}

func (q *Queries) UpdateClub(ctx context.Context, arg UpdateClubParams) (Club, error) {
	row := q.db.QueryRow(ctx, updateClub,
		arg.ID,
		arg.Name,
		arg.Specs,
		arg.Description,
		arg.TgUrl,
		arg.LogoUrl,
		arg.AdminContact,
		arg.FromOrg,
	)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Specs,
		&i.Description,
		&i.TgUrl,
		&i.LogoUrl,
		&i.AdminContact,
		&i.FromOrg,
	)
	return i, err
}
