// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feed.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const getEveryoneFeed = `-- name: GetEveryoneFeed :many
SELECT id, tag, owner_id, description, content_url, is_video, from_org, created_at, updated_at
FROM post
WHERE ($1::text IS NULL OR tag = $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetEveryoneFeedParams struct {
	Tag    *string `json:"tag"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) GetEveryoneFeed(ctx context.Context, arg GetEveryoneFeedParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getEveryoneFeed, arg.Tag, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.OwnerID,
			&i.Description,
			&i.ContentUrl,
			&i.IsVideo,
			&i.FromOrg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedByClubID = `-- name: GetFeedByClubID :many
SELECT id, tag, owner_id, description, content_url, is_video, from_org, created_at, updated_at
FROM post
WHERE owner_id = $1
  AND ($2::text IS NULL OR tag = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type GetFeedByClubIDParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Tag     *string   `json:"tag"`
	Offset  int32     `json:"offset"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) GetFeedByClubID(ctx context.Context, arg GetFeedByClubIDParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getFeedByClubID,
		arg.OwnerID,
		arg.Tag,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.OwnerID,
			&i.Description,
			&i.ContentUrl,
			&i.IsVideo,
			&i.FromOrg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedByClubIDCount = `-- name: GetFeedByClubIDCount :one
SELECT COUNT(*)
FROM post
WHERE owner_id = $1
  AND ($2::text IS NULL OR tag = $2)
`

type GetFeedByClubIDCountParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Tag     *string   `json:"tag"`
}

func (q *Queries) GetFeedByClubIDCount(ctx context.Context, arg GetFeedByClubIDCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getFeedByClubIDCount, arg.OwnerID, arg.Tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFeedCount = `-- name: GetFeedCount :one
SELECT COUNT(*)
FROM post
WHERE ($1::text IS NULL OR tag = $1)
`

func (q *Queries) GetFeedCount(ctx context.Context, tag *string) (int64, error) {
	row := q.db.QueryRow(ctx, getFeedCount, tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSubscriptionFeed = `-- name: GetSubscriptionFeed :many
SELECT DISTINCT p.id, p.tag, p.owner_id, p.description, p.content_url, p.is_video, p.from_org, p.created_at, p.updated_at
FROM post p
INNER JOIN subscription s ON p.owner_id = s.club_id
WHERE s.user_id = $1
  AND ($2::text IS NULL OR p.tag = $2)
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type GetSubscriptionFeedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Tag    *string   `json:"tag"`
	Offset int32     `json:"offset"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetSubscriptionFeed(ctx context.Context, arg GetSubscriptionFeedParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getSubscriptionFeed,
		arg.UserID,
		arg.Tag,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.OwnerID,
			&i.Description,
			&i.ContentUrl,
			&i.IsVideo,
			&i.FromOrg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionFeedCount = `-- name: GetSubscriptionFeedCount :one
SELECT COUNT(DISTINCT p.id)
FROM post p
INNER JOIN subscription s ON p.owner_id = s.club_id
WHERE s.user_id = $1
  AND ($2::text IS NULL OR p.tag = $2)
`

type GetSubscriptionFeedCountParams struct {
	UserID uuid.UUID `json:"user_id"`
	Tag    *string   `json:"tag"`
}

func (q *Queries) GetSubscriptionFeedCount(ctx context.Context, arg GetSubscriptionFeedCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSubscriptionFeedCount, arg.UserID, arg.Tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}
