// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID           uuid.UUID `json:"id"`
	FirstName    string    `json:"first_name"`
	SecondName   string    `json:"second_name"`
	FamilyName   string    `json:"family_name"`
	Age          int32     `json:"age"`
	PhoneNumber  string    `json:"phone_number"`
	Profession1  *string   `json:"profession_1"`
	Profession2  *string   `json:"profession_2"`
	Company      *string   `json:"company"`
	Future       *string   `json:"future"`
	University   *string   `json:"university"`
	Description  *string   `json:"description"`
	PasswordHash string    `json:"password_hash"`
}

type Club struct {
	ID           uuid.UUID `json:"id"`
	OwnerID      uuid.UUID `json:"owner_id"`
	Name         string    `json:"name"`
	Specs        string    `json:"specs"`
	Description  string    `json:"description"`
	TgUrl        string    `json:"tg_url"`
	LogoUrl      string    `json:"logo_url"`
	AdminContact string    `json:"admin_contact"`
	FromOrg      bool      `json:"from_org"`
}

type Org struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Name         string    `json:"name"`
	Specs        string    `json:"specs"`
	Description  string    `json:"description"`
	WebsiteUrl   string    `json:"website_url"`
	LogoUrl      string    `json:"logo_url"`
	VideoUrl     string    `json:"video_url"`
	AdminContact string    `json:"admin_contact"`
	Inn          string    `json:"inn"`
	Ogrn         string    `json:"ogrn"`
}

type Post struct {
	ID          uuid.UUID          `json:"id"`
	Tag         string             `json:"tag"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	Description string             `json:"description"`
	ContentUrl  string             `json:"content_url"`
	IsVideo     bool               `json:"is_video"`
	FromOrg     bool               `json:"from_org"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Subscription struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	ClubID uuid.UUID `json:"club_id"`
}
