// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: org.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createOrg = `-- name: CreateOrg :one
insert into org (
    user_id,
    name,
    specs,
    description,
    website_url,
    logo_url,
    video_url,
    admin_contact,
    inn,
    ogrn
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
returning id, user_id, name, specs, description, website_url, logo_url, video_url, admin_contact, inn, ogrn
`

type CreateOrgParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Name         string    `json:"name"`
	Specs        string    `json:"specs"`
	Description  string    `json:"description"`
	WebsiteUrl   string    `json:"website_url"`
	LogoUrl      string    `json:"logo_url"`
	VideoUrl     string    `json:"video_url"`
	AdminContact string    `json:"admin_contact"`
	Inn          string    `json:"inn"`
	Ogrn         string    `json:"ogrn"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg,
		arg.UserID,
		arg.Name,
		arg.Specs,
		arg.Description,
		arg.WebsiteUrl,
		arg.LogoUrl,
		arg.VideoUrl,
		arg.AdminContact,
		arg.Inn,
		arg.Ogrn,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Specs,
		&i.Description,
		&i.WebsiteUrl,
		&i.LogoUrl,
		&i.VideoUrl,
		&i.AdminContact,
		&i.Inn,
		&i.Ogrn,
	)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :exec
delete from org where id = $1
`

func (q *Queries) DeleteOrg(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrg, id)
	return err
}

const getOrgByID = `-- name: GetOrgByID :one
select id, user_id, name, specs, description, website_url, logo_url, video_url, admin_contact, inn, ogrn from org where id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id uuid.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Specs,
		&i.Description,
		&i.WebsiteUrl,
		&i.LogoUrl,
		&i.VideoUrl,
		&i.AdminContact,
		&i.Inn,
		&i.Ogrn,
	)
	return i, err
}

const updateOrg = `-- name: UpdateOrg :one
update org set
    name           = coalesce($2, name),
    specs          = coalesce($3, specs),
    description    = coalesce($4, description),
    website_url    = coalesce($5, website_url),
    logo_url       = coalesce($6, logo_url),
    video_url      = coalesce($7, video_url),
    admin_contact  = coalesce($8, admin_contact),
    inn            = coalesce($9, inn),
    ogrn           = coalesce($10, ogrn)
where id = $1
returning id, user_id, name, specs, description, website_url, logo_url, video_url, admin_contact, inn, ogrn
`

type UpdateOrgParams struct {
	ID           uuid.UUID `json:"id"`
	Name         *string   `json:"name"`
	Specs        *string   `json:"specs"`
	Description  *string   `json:"description"`
	WebsiteUrl   *string   `json:"website_url"`
	LogoUrl      *string   `json:"logo_url"`
	VideoUrl     *string   `json:"video_url"`
	AdminContact *string   `json:"admin_contact"`
	Inn          *string   `json:"inn"`
	Ogrn         *string   `json:"ogrn"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg,
		arg.ID,
		arg.Name,
		arg.Specs,
		arg.Description,
		arg.WebsiteUrl,
		arg.LogoUrl,
		arg.VideoUrl,
		arg.AdminContact,
		arg.Inn,
		arg.Ogrn,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Specs,
		&i.Description,
		&i.WebsiteUrl,
		&i.LogoUrl,
		&i.VideoUrl,
		&i.AdminContact,
		&i.Inn,
		&i.Ogrn,
	)
	return i, err
}
