// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: post.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO post (
    tag,
    owner_id,
    description,
    image_url,
    from_org
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, tag, owner_id, description, image_url, from_org, created_at, updated_at
`

type CreatePostParams struct {
	Tag         string    `json:"tag"`
	OwnerID     uuid.UUID `json:"owner_id"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	FromOrg     bool      `json:"from_org"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Tag,
		arg.OwnerID,
		arg.Description,
		arg.ImageUrl,
		arg.FromOrg,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.OwnerID,
		&i.Description,
		&i.ImageUrl,
		&i.FromOrg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM post
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, tag, owner_id, description, image_url, from_org, created_at, updated_at FROM post
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.OwnerID,
		&i.Description,
		&i.ImageUrl,
		&i.FromOrg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByOwnerId = `-- name: GetPostByOwnerId :one
SELECT id, tag, owner_id, description, image_url, from_org, created_at, updated_at FROM post
WHERE owner_id = $1 LIMIT 1
`

func (q *Queries) GetPostByOwnerId(ctx context.Context, ownerID uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByOwnerId, ownerID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.OwnerID,
		&i.Description,
		&i.ImageUrl,
		&i.FromOrg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE post
SET 
    tag = $2,
    description = $3,
    image_url = $4,
    from_org = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tag, owner_id, description, image_url, from_org, created_at, updated_at
`

type UpdatePostParams struct {
	ID          uuid.UUID `json:"id"`
	Tag         string    `json:"tag"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	FromOrg     bool      `json:"from_org"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Tag,
		arg.Description,
		arg.ImageUrl,
		arg.FromOrg,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.OwnerID,
		&i.Description,
		&i.ImageUrl,
		&i.FromOrg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
