// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: subscription.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
insert into subscription (
    user_id,
    club_id
) values (
    $1, $2
)
returning id, user_id, club_id
`

type CreateSubscriptionParams struct {
	UserID uuid.UUID `json:"user_id"`
	ClubID uuid.UUID `json:"club_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.ClubID)
	var i Subscription
	err := row.Scan(&i.ID, &i.UserID, &i.ClubID)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
delete from subscription
where id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const deleteSubscriptionByUserAndClub = `-- name: DeleteSubscriptionByUserAndClub :exec
delete from subscription
where user_id = $1 and club_id = $2
`

type DeleteSubscriptionByUserAndClubParams struct {
	UserID uuid.UUID `json:"user_id"`
	ClubID uuid.UUID `json:"club_id"`
}

func (q *Queries) DeleteSubscriptionByUserAndClub(ctx context.Context, arg DeleteSubscriptionByUserAndClubParams) error {
	_, err := q.db.Exec(ctx, deleteSubscriptionByUserAndClub, arg.UserID, arg.ClubID)
	return err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
select id, user_id, club_id from subscription
where id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(&i.ID, &i.UserID, &i.ClubID)
	return i, err
}

const getSubscriptionByUserAndClub = `-- name: GetSubscriptionByUserAndClub :one
select id, user_id, club_id from subscription
where user_id = $1 and club_id = $2
`

type GetSubscriptionByUserAndClubParams struct {
	UserID uuid.UUID `json:"user_id"`
	ClubID uuid.UUID `json:"club_id"`
}

func (q *Queries) GetSubscriptionByUserAndClub(ctx context.Context, arg GetSubscriptionByUserAndClubParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserAndClub, arg.UserID, arg.ClubID)
	var i Subscription
	err := row.Scan(&i.ID, &i.UserID, &i.ClubID)
	return i, err
}

const getSubscriptionsByClubID = `-- name: GetSubscriptionsByClubID :many
select id, user_id, club_id from subscription
where club_id = $1
`

func (q *Queries) GetSubscriptionsByClubID(ctx context.Context, clubID uuid.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsByClubID, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(&i.ID, &i.UserID, &i.ClubID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsByUserID = `-- name: GetSubscriptionsByUserID :many
select id, user_id, club_id from subscription
where user_id = $1
`

func (q *Queries) GetSubscriptionsByUserID(ctx context.Context, userID uuid.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(&i.ID, &i.UserID, &i.ClubID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
